name: Dave.com Automated Tests
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 8 * * *'
jobs:
  dave-com-production-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress Tests Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          spec: |
            cypress/integration/**/*spec.js
          config-file: cypress/env/production.json
          config: video=true
      - name: Upload Screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload Videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Copy Videos for Test Report
        run: |
          mkdir public
          cp -r cypress/videos public/videos
      - name: Merge Test Result Files
        run: npm run report:merge
      - name: Generate HTML report
        run: npm run report:generate
      - name: Deploy Cypress Test Report 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      - name: Report Url 
        run: echo "https://zaidisyed1991.github.io/dave-com-tests-master/index.html"
        shell: bash
